### ISSUE TITLE
READMEの修正

### ISSUE THREAD

**Issue by shira79** [ebinase/othello#39]
## リポジトリのURLが違う
> git clone https://github.com/ebinase/nextjs-tutorial.git

## アプリケーションキー発行コマンドの実行タイミング

>  アプリケーションキー発行
> $ ./vendor/bin/sail artisan key:generate

上記のコマンドはコンテナの起動後に打たないとエラーになる。ので別途記載したほうが親切かも。

```
Sail is not running
```

**Comment by ebinase** [comment]
@shira79 
指摘ありがとう！

> リポジトリのURLが違う

修正します！

> アプリケーションキー発行コマンドの実行タイミング

.env系のセットアップの前にupするように変更します！

**Comment by shira79** [comment]
はやいｗ あざす^^

あと、スレ違いかもだが
`APP_DEBUG=true`のままだと、オセロの石を打てないのだが、これは確認済み？？

**Comment by ebinase** [comment]
@shira79 
README 更新した！
ご確認くださいmm
(OKそうだったらissueクローズしちゃってOK)


> APP_DEBUG=trueのままだと、オセロの石を打てないのだが、これは確認済み？？

知らなかった。。。
手元で現象が再現できたんで別issue立てて対応する！

**Comment by ebinase** [comment]
@shira79 
いったんデバッグバーが原因になっていたことだけは確認できたからmainに反映しましたー
最新版のpullをお願いしますmm

あと、原因思いついたらここで伝えてもらえると嬉しい！
https://github.com/ebinase/othello/issues/40
