### ISSUE TITLE
[Bug]: 開発環境でオセロの石を打てない

### ISSUE THREAD

**Issue by ebinase** [ebinase/othello#40]
### 概要

> APP_DEBUG=trueのままだと、オセロの石を打てない
https://github.com/ebinase/othello/issues/39#issuecomment-1073172921

盤面の置ける場所をクリックしても、盤面が更新されずに再度盤面が表示される
* 更新用のURIからリダイレクトされている様子もない
* URIに`method=&uri=&ip=`というクエリパラメータが付与されている
* デバッグバー( `barryvdh/laravel-debugbar`)を導入した後から発生

### 再現手順

1. `.env`内で`APP_DEBUG=true`であることを確認する
2. sailコマンドを使って開発サーバを立ち上げる
3. 任意のモードでゲームを開始
4. 置ける場所をクリックする

### 期待した動作

コマを置く

### Version

ボット対戦モード

**Comment by ebinase** [comment]
デバッグバーを削除したところ、今まで通り動作するようになったことを確認。
いったんこのままmainに反映。

```
-  "barryvdh/laravel-debugbar": "^3.6",
```

調査は継続し、解決出来次第デバッグバーを再導入する

**Comment by shira79** [comment]
原因見つけた〜🥇 

`resources/views/game/board.blade.php`の中でformタグをsubmitしてるんだけど、、、

```js
         $(function(){
            $('.field').on('click', function () {
                const [x, y] = [$(this).data('position-x'), $(this).data('position-y')];
                $('#x').val(x);
                $('#y').val(y);
                $('form').submit();
            });
        });
```

debugbarが有効になっているとformタグがもう1つ描画されているね^^
こっちのformがsubmitされてしまっているから`method=&uri=&ip=` がぶら下がっているというw

<img width="1016" alt="スクリーンショット 2022-03-21 1 37 12" src="https://user-images.githubusercontent.com/42834409/159173205-b3763954-227d-40b2-b965-9e40aaec85da.png">

formにidを付与することで正常に動作することを確認しました^^

**Comment by ebinase** [comment]
@shira79 
発見&修正ありがとう！

作業は fix/#40 ブランチ
プルリクはテンプレートに沿って作成してレビュアーをebinseに設定してください！

**Comment by ebinase** [comment]
@shira79 
mainにマージさせて頂きました！

今後の活躍も楽しみにしてます。ご協力ありがとうございました:rocket:
